
"""
Interview-level end-to-end AI test automation pipeline.

Pipeline:

Source documents
    ↓
LLM test generation
    ↓
Validated Excel workbook
    ↓
Capability-based pytest generation
    ↓
Deterministic simulator
    ↓
pytest execution
    ↓
Failure analysis with RAG
    ↓
Final failure-analysis report

The LLM generates test specifications.
The deterministic capability layer controls executable automation.
The RAG failure analyzer analyzes pytest failures using
historical test-case context retrieved from FAISS.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
import sys
from typing import Any


BASE_DIR = Path(__file__).resolve().parents[1]

if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))


from test_generation.generate_pytest_from_docs import (
    generate_excel,
)

from test_generation.generate_tests_from_docs import (
    generate,
)

from ai_engine.failure_analyzer import FailureAnalyzer


WORKBOOK = BASE_DIR / "generated_tests.xlsx"

GENERATED_TEST = (
    BASE_DIR
    / "tests"
    / "generated"
    / "test_generated_from_excel.py"
)

REPORT_DIR = BASE_DIR / "reports"

FAILURE_REPORT = (
    REPORT_DIR
    / "ai_failure_analysis_report.json"
)


def run_pytest() -> dict[str, Any]:
    """
    Execute the pytest file generated from the current workbook.
    """

    command = [
        sys.executable,
        "-m",
        "pytest",
        str(GENERATED_TEST),
        "-v",
    ]

    result = subprocess.run(
        command,
        cwd=BASE_DIR,
        capture_output=True,
        text=True,
    )

    output = (
        result.stdout
        + "\n"
        + result.stderr
    )

    return {
        "success": result.returncode == 0,
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "output": output,
    }


def analyze_failures(
    pytest_result: dict[str, Any],
) -> dict[str, Any]:
    """
    Analyze pytest failures using the RAG-based failure analyzer.

    The complete pytest execution output is passed to the existing
    FailureAnalyzer. The analyzer retrieves similar historical
    test cases through SmartRetriever/FAISS and sends the retrieved
    context to Llama3.
    """

    REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    if pytest_result["success"]:
        report = {
            "status": "NO_FAILURES",
            "message": (
                "All generated pytest tests passed. "
                "RAG failure analysis was not required."
            ),
        }

        FAILURE_REPORT.write_text(
            json.dumps(
                report,
                indent=2,
                default=str,
            ),
            encoding="utf-8",
        )

        return report

    failure_log = pytest_result["output"]

    print("\n" + "=" * 80)
    print("RAG FAILURE ANALYSIS")
    print("=" * 80)

    analyzer = FailureAnalyzer()

    analysis = analyzer.analyze(
        failure_log
    )

    report = {
        "status": "FAILURES_ANALYZED",
        "pytest_returncode": pytest_result["returncode"],
        "failure_log": failure_log,
        "analysis": analysis,
    }

    FAILURE_REPORT.write_text(
        json.dumps(
            report,
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )

    print(
        f"\nFailure-analysis report: "
        f"{FAILURE_REPORT}"
    )

    return report


def run_pipeline(
    count: int = 5,
    force_ai: bool = False,
) -> dict[str, Any]:
    """
    Run the complete:

        LLM → Excel → pytest → RAG failure analysis

    pipeline.

    When force_ai=True, a new test specification workbook is
    generated by the LLM. It is NOT loaded from the cached
    interview workbook.
    """

    print("=" * 80)
    print("AI TEST AUTOMATION PIPELINE")
    print("=" * 80)

    print(
        "\n[1/4] Generating AI test specifications..."
    )

    workbook = generate_excel(
        count=count,
        force=force_ai,
        use_cache=not force_ai,
    )

    workbook_path = (
        Path(workbook)
        if workbook is not None
        else WORKBOOK
    )

    if not workbook_path.exists():
        raise FileNotFoundError(
            "Expected workbook was not created: "
            f"{workbook_path}"
        )

    print(
        f"Workbook ready: {workbook_path}"
    )

    print(
        "\n[2/4] Converting current Excel "
        "test cases to pytest..."
    )

    generation_result = generate(
        workbook_path
    )

    if not GENERATED_TEST.exists():
        raise FileNotFoundError(
            "Pytest generation reported success, "
            "but the generated test file does not exist: "
            f"{GENERATED_TEST}"
        )

    print(
        f"Generated pytest file: {GENERATED_TEST}"
    )

    print(
        "\n[3/4] Executing generated pytest tests..."
    )

    pytest_result = run_pytest()

    print(pytest_result["stdout"])

    if pytest_result["stderr"]:
        print(pytest_result["stderr"])

    print(
        "\n[4/4] Processing pytest result..."
    )

    failure_analysis = analyze_failures(
        pytest_result
    )

    return {
        "workbook": str(workbook_path),
        "generation": generation_result,
        "pytest": pytest_result,
        "failure_analysis": failure_analysis,
    }


def main() -> int:
    """
    CLI entry point.

    Recommended interview/demo command:

        python core/ai_test_pipeline.py --ai --count 5
    """

    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Run the complete "
            "LLM → Excel → pytest → RAG "
            "failure-analysis pipeline."
        )
    )

    parser.add_argument(
        "--count",
        type=int,
        default=5,
        help="Number of AI-generated test cases.",
    )

    parser.add_argument(
        "--ai",
        action="store_true",
        help=(
            "Generate a new workbook using the "
            "real LLM. Without this flag the validated "
            "cached workbook may be used."
        ),
    )

    args = parser.parse_args()

    result = run_pipeline(
        count=args.count,
        force_ai=args.ai,
    )

    print("\n" + "=" * 80)
    print("PIPELINE SUMMARY")
    print("=" * 80)

    print(
        f"Workbook: {result['workbook']}"
    )

    print(
        "Pytest success: "
        f"{result['pytest']['success']}"
    )

    print(
        "Pytest return code: "
        f"{result['pytest']['returncode']}"
    )

    print(
        "Failure analysis status: "
        f"{result['failure_analysis']['status']}"
    )

    print(
        "Failure report: "
        f"{FAILURE_REPORT}"
    )

    return (
        0
        if result["pytest"]["success"]
        else 1
    )


if __name__ == "__main__":
    raise SystemExit(main())

